import { MaterialIcons } from "@expo/vector-icons";
import { StatusBar } from "expo-status-bar";
import { ScrollView, StyleSheet, View } from "react-native";
import { TableRow, TableRowGroup } from "@/src/components/ui";
import { TText, TView, useTheme } from "@/src/theme";

export function HelpScreen() {
  const { isDark, theme } = useTheme();

  return (
    <TView variant="background" style={{ flex: 1 }}>
      <ScrollView style={{ flex: 1, paddingTop: 16 }}>
        <TableRowGroup
          title="What is a Discord Data Package?"
          description="Your exported data from Discord that includes messages, account details, settings, and more."
        >
          <TableRow>
            <View style={styles.tableRowContent}>
              <MaterialIcons name="inventory" size={24} color={theme.primary} />
              <View style={styles.textContainer}>
                <TText
                  variant="primary"
                  weight="semibold"
                  style={{ fontSize: 16, lineHeight: 20 }}
                >
                  Contents
                </TText>
                <TText
                  variant="secondary"
                  style={{ fontSize: 12, lineHeight: 16 }}
                >
                  Messages, channels, servers, profile, billing history,
                  security events, and settings.
                </TText>
              </View>
            </View>
          </TableRow>
          <TableRow>
            <View style={styles.tableRowContent}>
              <MaterialIcons name="lock" size={24} color={theme.primary} />
              <View style={styles.textContainer}>
                <TText
                  variant="primary"
                  weight="semibold"
                  style={{ fontSize: 16, lineHeight: 20 }}
                >
                  Privacy
                </TText>
                <TText
                  variant="secondary"
                  style={{ fontSize: 12, lineHeight: 16 }}
                >
                  The package is generated by Discord and stays on your device
                  when using this app.
                </TText>
              </View>
            </View>
          </TableRow>
        </TableRowGroup>

        <TableRowGroup
          title="How to Get Your Data Package"
          description="Request and download your package from Discord on any platform."
        >
          <TableRow>
            <View style={styles.tableRowContent}>
              <MaterialIcons name="language" size={24} color={theme.primary} />
              <View style={styles.textContainer}>
                <TText
                  variant="primary"
                  weight="semibold"
                  style={{ fontSize: 16, lineHeight: 20 }}
                >
                  Web
                </TText>
                <TText
                  variant="secondary"
                  style={{ fontSize: 12, lineHeight: 16 }}
                >
                  User Settings → Privacy & Safety → Request all of my Data.
                  You'll receive an email when it's ready.
                </TText>
              </View>
            </View>
          </TableRow>
          <TableRow>
            <View style={styles.tableRowContent}>
              <MaterialIcons name="computer" size={24} color={theme.primary} />
              <View style={styles.textContainer}>
                <TText
                  variant="primary"
                  weight="semibold"
                  style={{ fontSize: 16, lineHeight: 20 }}
                >
                  Desktop
                </TText>
                <TText
                  variant="secondary"
                  style={{ fontSize: 12, lineHeight: 16 }}
                >
                  Same path as Web in the desktop app. Download the ZIP when
                  available.
                </TText>
              </View>
            </View>
          </TableRow>
          <TableRow>
            <View style={styles.tableRowContent}>
              <MaterialIcons
                name="phone-android"
                size={24}
                color={theme.primary}
              />
              <View style={styles.textContainer}>
                <TText
                  variant="primary"
                  weight="semibold"
                  style={{ fontSize: 16, lineHeight: 20 }}
                >
                  Mobile
                </TText>
                <TText
                  variant="secondary"
                  style={{ fontSize: 12, lineHeight: 16 }}
                >
                  Settings → Privacy & Safety → Request Data. Save the ZIP to
                  your files when ready.
                </TText>
              </View>
            </View>
          </TableRow>
        </TableRowGroup>

        <TableRowGroup
          title="How This App Processes Your Package"
          description="Processing happens on-device using a Rust core for speed and privacy."
        >
          <TableRow>
            <View style={styles.tableRowContent}>
              <MaterialIcons name="speed" size={24} color={theme.primary} />
              <View style={styles.textContainer}>
                <TText
                  variant="primary"
                  weight="semibold"
                  style={{ fontSize: 16, lineHeight: 20 }}
                >
                  Rust Engine
                </TText>
                <TText
                  variant="secondary"
                  style={{ fontSize: 12, lineHeight: 16 }}
                >
                  A Rust framework parses the ZIP, extracts data, and computes
                  analytics locally without sending it anywhere.
                </TText>
              </View>
            </View>
          </TableRow>
          <TableRow>
            <View style={styles.tableRowContent}>
              <MaterialIcons name="security" size={24} color={theme.primary} />
              <View style={styles.textContainer}>
                <TText
                  variant="primary"
                  weight="semibold"
                  style={{ fontSize: 16, lineHeight: 20 }}
                >
                  On-Device Privacy
                </TText>
                <TText
                  variant="secondary"
                  style={{ fontSize: 12, lineHeight: 16 }}
                >
                  No servers involved. You can cancel processing anytime from
                  the progress screen.
                </TText>
              </View>
            </View>
          </TableRow>
        </TableRowGroup>

        <View style={{ height: 24 }} />
      </ScrollView>
      <StatusBar style={isDark ? "light" : "dark"} />
    </TView>
  );
}

const styles = StyleSheet.create({
  tableRowContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  textContainer: {
    flexDirection: "column",
    justifyContent: "center",
    flex: 1,
    marginLeft: 16,
  },
});
