name: Release iOS

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo target
        uses: actions/cache@v4
        with:
          path: dpkg-rs/target
          key: ${{ runner.os }}-cargo-target-ios-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install npm dependencies
        run: npm install

      - name: Add ios target
        run: rustup target add aarch64-apple-ios

      - name: Build Rust library
        run: ./build-ios-lib.sh

      - name: Build the app
        run: eas build --platform ios --non-interactive --local --profile production --output ./build.ipa

      - name: Submit the build
        run: eas submit --platform ios --non-interactive --profile production --path ./build.ipa