name: Release Android

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Type of release"
        required: true
        default: "internal"
        type: choice
        options:
            - internal
            - beta
            - production

jobs:
  release:
    runs-on: macos-15
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo target
        uses: actions/cache@v4
        with:
          path: dpkg-rs/target
          key: ${{ runner.os }}-cargo-target-android-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install npm dependencies
        run: npm install

      - name: Add Android targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

      - name: Build Rust library
        run: ./build-android-lib.sh

      - name: Build the app
        run: eas build --platform android --non-interactive --local --profile production --output ./build.aab

      - name: Submit the build
        run: eas submit --platform android --non-interactive --profile ${{ inputs.release_type }} --no-wait --path ./build.aab